run:
  build:
    - apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0
    - rm -rf ~/.cache/pip  # Clear pip cache
    - pip install --no-cache-dir -r requirements.txt  # Force a fresh installation
  command: uvicorn app.main:app --host 0.0.0.0 --port 8000
